# all required
otmetaComponent: myOpentableService
# we won't be using this for this demo
#namespace: consumer
image:
  registry: docker.otenv.com
  repository: demo-server
  tag: demo-tag

ports:
  - http
  - jmx
  - actuator

resourcesReq:
  memory: 1000Mi
  cpu: 500m

replicaCount: 2

