# all required
otmetaComponent: myOpentableService
# we override this for this demo
namespace: consumer
image:
  registry: docker.otenv.com
  repository: k8s-training
  tag: demo-server

ports:
  - http
  - jmx
  - actuator

env:
  ot.announce.enabled: "false"

resourcesReq:
  memory: 1000Mi
  cpu: 500m
