# all required
otmetaComponent: myOpentableService
# we override this for this demo
namespace: consumer
image:
  repository: k8s-training
  tag: demo-server

# C#/node people need just http, but java services should use these settings normally
ports:
  - http
  - jmx
  - actuator

env:
  ot.announce.enabled: "false"

resourcesReq:
  memory: 1000Mi
  cpu: 500m
