---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: ws-{{ required "namespace required" .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
    otmetaComponent: {{ required ".Values.otmetaComponent required" .Values.otmetaComponent }}
    preset: "basic"
    needs-instance-no: "yes"
spec:
  replicas: {{ required ".Values.replicaCount required" .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.maxSurge | default "50%" }}
      {{- if gt (.Values.replicaCount | int) 1 }}
      maxUnavailable: {{ if hasKey .Values "maxUnavailable" }}{{.Values.maxUnavailable}}{{ else }}1{{ end }}
      {{- else }}
      maxUnavailable: 0
      {{- end }}
  template:
    metadata:
      annotations:
        app.kubernetes.io/version: {{ required ".Values.image.tag is required " .Values.image.tag | quote }}
        deployed: {{ date "20060102150405" now   | quote }}
      labels:
        otmetaComponent: {{ required ".Values.otmetaComponent required" .Values.otmetaComponent }}
        preset: "basic"
        needs-instance-no: "yes"
        app: {{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: 3000
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds | default 60 }}
      restartPolicy: {{ .Values.restartPolicy | default "Always" }}
      enableServiceLinks: false
      containers:
        - name: {{ required ".Values.image.repository is required" .Values.image.repository | quote }}
          image: '{{ default "docker.otenv.com" .Values.image.registry}}/{{ required ".Values.image.repository is required" .Values.image.repository }}:{{ required ".Values.image.tag is required" .Values.image.tag }}'
          imagePullPolicy: {{ default "Always" .Values.image.pullPolicy }}

{{- /* ENV variables */}}
          env:
          - name: ESTIMATED_INSTANCE_COUNT
            value: {{ .Values.replicaCount | quote }}
          - name: OT_BUILD_IMAGE
            value: {{ default "docker.otenv.com" .Values.image.registry}}/{{ required ".Values.image.repository is required" .Values.image.repository }}
          - name: OT_BUILD_TAG
            value: {{ required ".Values.image.tag is required" .Values.image.tag | quote }}
          - name: K8S_SERVICE_NAME
            value: {{ .Release.Name }}
          {{- if not .Values.readiness.optOut }}
          - name: READINESS_PROBE
            value: "true"
          {{- end }}
{{- /* PORT_$NAME in ENV */}}
{{- with .Values.ports }}
{{- template "deployment.envports" .}}
{{- end }}
{{- /* PORTS from values */}}
{{- with .Values.ports }}
          ports:
{{- template "deployment.ports" .}}
{{- end -}}

{{- /* PROBES */}}
{{- template  "deployment.probes".}}

{{- /* CPU and MEMORY reqest/limit */}}
          resources:
            requests:
              memory: {{ .Values.resourcesReq.memory | default "128Mi" }}
              cpu: {{ .Values.resourcesReq.cpu | default "100m" }}
{{- if .Values.resourcesLim }}
            limits:
              memory: {{ .Values.resourcesLim.memory | default "128Mi" }}
              cpu: {{ .Values.resourcesLim.cpu | default "100m" }}
{{- else }}
            limits:
              memory: {{ .Values.resourcesReq.memory | default "512Mi" }}
              cpu: {{ .Values.resourcesReq.cpu | default "100m" }}


{{- end -}}
        {{- /* sidecars */}}
        {{- if .Values.sandbox.enabled }}
        {{- include "sandbox.sidecar" . | nindent 8}}
        {{- end }}
